name: Fifth Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/**'
      - '**.py'
      - '**.md'
  pull_request:
    branches: ["main"]

jobs:
  Python-linux-Job:
    name: Python Linux Job
    runs-on: ubuntu-latest
    steps:
      - name: Python shell
        run: |
          import platform
          print(platform.processor())
        shell: python
  Python-windows-Job:
    name: Python Job
    runs-on: windows-latest
    steps:
      - name: Powershell
        run: Get-Location
      - name: Powershell Bash
        run: pwd
        shell: bash
