name: First Workflow

# events: create, fork, issues, issue_comment, watch, discussion, repository_dispatch, schedule, workflow_call...
# on: workflow_dispatch
# on: push
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/**'
      - '**.py'
      - '**.md'
  pull_request:
    branches: ["main"]

jobs:
  Python-Job:
    name: Python Job
    runs-on: ubuntu-latest
    steps:
      - name: Python shell
        run: |
          import platform
          print(platform.processor())
        shell: python
