name: Fourth Workflow (Windows & Mac OS)

# events: create, fork, issues, issue_comment, watch, discussion, repository_dispatch, schedule, workflow_call...
# on: workflow_dispatch
# on: push
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches: ["main"]

jobs:
  windows-job:
    name: Windows Job
    runs-on: windows-latest
    steps:
      - name: Checkout...
        uses: actions/checkout@v2

  mac-job:
    name: Mac OS Job
    runs-on: macos-latest
    steps:
      - name: Checkout...
        uses: actions/checkout@v2
