name: Second Workflow

on: ["workflow_dispatch", "push"]

jobs:
  Checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  Node:
    name: Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Node.js Version
        run: node -v
      - name: Npm Version
        run: npm -v