name: Third Workflow

# events: create, fork, issues, issue_comment, watch, discussion, repository_dispatch, schedule, workflow_call...
# on: workflow_dispatch
# on: push
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/**'
      - '**.py'
      - '**.md'
  pull_request:
    branches: ["main"]

jobs:
  shell:
    name: shell Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout...
        uses: actions/checkout@v2
      - name: First Step
        run: 'echo "First Job: First Step..."'
      - name: Second Step
        run: |
          echo "Commands: Start..."
          whoami
          env
          ls -a
          df
          echo "Commands: End."
      - name: Third Step
        run: sh ./github-shell.sh
